name: test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install  gtest and gmock
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev libgmock-dev

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          cmake --build build
